theme: minima
title: Haciendo el curso
author: Diego Rodriguez Perez
email:alu0101203980@ull.edu.es
description: > # this means to ignore newlines until "baseurl:"
  Aqui probando cosas
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
